POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test",
    "author": "Goku",
    "url": "example.com",
    "likes": 3,
    "userId": "63b9144d51e913c5ae20c8f3"
}
###
POST http://localhost:8080/api/blogs/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzYmQxNDY5OGUzZmZiNjliY2YwY2ZlMiIsImlhdCI6MTY3MzQyMzAwOH0.hGnaqZQEQR_jmvqPh6s2bwZr9BiVqg7SZsOkXJxjv2E

{
    "title": "Authorizing a token with middleware",
    "author": "Goten",
    "url": "example.com",
    "likes": 8
}
###
POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test 2",
    "author": "Vegeta",
    "url": "example.com",
    "likes": 5,
    "userId": "63bd14698e3ffb69bcf0cfe2"
}
###
POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test 3",
    "author": "Gohan",
    "url": "example.com",
    "likes": 9,
    "userId":"63b91343e1077262b90497ea"
}
###
POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test 4",
    "author": "Bulma",
    "url": "example.com",
    "likes": 8
}
###
POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test 5",
    "author": "Goten",
    "url": "example.com"
}
###
POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test 6",
    "author": "Chichi",
    "url": "example.com",
    "likes": 12
}
###
DELETE  http://localhost:8080/api/blogs/63bd12f4b635042e554ee656