POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test",
    "author": "Goku",
    "url": "example.com",
    "likes": 3
}
###
POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test 2",
    "author": "Vegeta",
    "url": "example.com",
    "likes": 5
}
###
POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test 3",
    "author": "Gohan",
    "url": "example.com",
    "likes": 9
}
###
POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test 4",
    "author": "Bulma",
    "url": "example.com",
    "likes": 8
}
###
POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test 5",
    "author": "Goten",
    "url": "example.com"
}
###
POST http://localhost:8080/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test 6",
    "author": "Chichi",
    "url": "example.com",
    "likes": 12
}