POST http://localhost:8080/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}
###
POST http://localhost:8080/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "name": "Admin",
    "password": "tester"
}
###
POST http://localhost:8080/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "error",
    "name": "Error",
    "password": "12"
}